# Paths
gemma_dir:       ~/Thesis/data/MultiConAD/gemma
trill_dir:       ~/Thesis/data/MultiConAD/trillsson
speakers_json:    ~/Thesis/data/MultiConAD/speakers.json
train_jsonl:     ~/Thesis/data/MultiConAD/train_English.jsonl
test_jsonl:      ~/Thesis/data/MultiConAD/test_English.jsonl
results_dir:     ~/Thesis/results

# Experiment
experiment_name: ConGrAD-VIS
experiment_description: "First test with visualizer"
base_seed: 24
n_runs: 1

# Embedding dims
audio_dim: 1024
text_dim:  768

# Model
n_classes:    3
d_model:      128
ca_heads:     4
ca_layers:    1
rgat_heads:   4
rgat_layers:  2
graph_window: 5

# Regularization
dropout:      0.5
drop_edge:    0.1
patience:     10
weight_decay: 0.0001

# Training
device:     cuda
batch_size: 16
lr:         0.0001
epochs:     30

# Data Augmentation
balanced_mixup: true
mixup_alpha:    0.1

# Visualization
visualizations: true   # set false to skip t-SNE and graph plots

# Hyperparameter Optimization
hpo_epochs: 20
hpo_trials: 50
