# Paths
gemma_dir:       ~/Thesis/data/MultiConAD/gemma
trill_dir:       ~/Thesis/data/MultiConAD/trillsson
speakers_json:    ~/Thesis/data/MultiConAD/speakers.json
train_jsonl:     ~/Thesis/data/MultiConAD/train_English.jsonl
test_jsonl:      ~/Thesis/data/MultiConAD/test_English.jsonl
results_dir:     ~/Thesis/results

# Experiment
experiment_name: ConGrAD-BMU-0_1
experiment_description: "ConGrAD with Balanced-MixUp alpha-0.1"
base_seed: 24
n_runs: 1

# Embedding dims
audio_dim: 1024
text_dim:  768

# Model
n_classes:     3
d_model:       128
ca_heads:      8
ca_layers:     3
rgat_heads:    8
rgat_layers:   2
graph_window:  5
skip_log_base: 2       # log base of the graph skip-edges

# Regularization
dropout:        0.4
drop_edge:      0.1
weight_decay:   0.0001
balanced_mixup: true
mixup_alpha:    0.1    # as a grows we have more balanced classes, but risk more overfitting

# Training
device:     cuda
batch_size: 16
lr:         0.0001
epochs:     60
patience:   10

# Hyperparameter Optiomization
hpo_epochs: 20 
hpo_trials: 50
